### ISSUE TITLE
Chaos Source doesn't have this limitation

### ISSUE THREAD

**Issue by Gocnak** [MrKleiner/cbtool#1]
Howdy! 👋 🤠 

Chaos Source and its derived games do not have this limitation. The code that limits the smallest cubemap is 1x1, and we automatically add the `No Minimum Mipmap` flag to cubemaps anyways. The limit is now actually opt-in, via the `mostmips` vmt flag.

See this for more info:
https://github.com/ChaosInitiative/Chaos-Source/issues/621#issuecomment-1342027349

I'm not sure about other Source games with PBR, but please remove Chaos games (Momentum Mod, P2CE) from the README as it doesn't apply to us. Thank you!

**Comment by WhiteRedDragons** [comment]
Hi! If you are curious : 
Some mods use a modified version of the momentum mod's Shader on sdk2013mp/sdk2013sp. ( Like Map-Labs )
The code on the Repo still tries to force load the Cubemaps with this flag ( see line 192 on the cpp ). We were not aware this wasn't even an issue anymore on Chaos Source, because this was still in the code
( _and_ ofc because we just didn't know :smiling_face_with_tear: )

We will take this into consideration and update the readme accordingly, in a bit, thanks for pointing this out!

**Comment by MrKleiner** [comment]
Fixed
